"""Add wallet leagues and modify users

Revision ID: a40b09d5fe9c
Revises: 1f9c3b0e9ce9
Create Date: 2025-10-24 06:46:19.209668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40b09d5fe9c'
down_revision: Union[str, Sequence[str], None] = '1f9c3b0e9ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# define the enum type once
role_enum = sa.Enum('user', 'admin', 'super_admin', name='role')
status_enum = sa.Enum('active', 'suspended', name='userstatus')

def upgrade() -> None:
    """Upgrade schema."""
    # 1) create enum type
    role_enum.create(op.get_bind(), checkfirst=True)
    status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'ongoing', 'completed', name='leaguestatus'), nullable=False),
    sa.Column('entry_fee_cents', sa.Integer(), nullable=False),
    sa.Column('prize_scheme', sa.JSON(), nullable=False),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('league_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'league_id')
    )
    op.add_column('users', sa.Column('role', role_enum, nullable=False, server_default='user'))
    op.add_column('users', sa.Column('status', status_enum, nullable=False, server_default='active'))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('kyc_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'kyc_level')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table('league_members')
    op.drop_table('leagues')
    # ### end Alembic commands ###
